drop table goods cascade constraints PURGE;
drop table PIERS cascade constraints PURGE;
drop table ships cascade constraints PURGE;
drop table STATEMENTS cascade constraints PURGE;
drop table statements_types cascade constraints PURGE;
drop table statements_statuses cascade constraints PURGE;
drop table USERS cascade constraints PURGE;
drop table USERS_ROLES cascade constraints PURGE;
drop table USERS_STATUSES cascade constraints PURGE;